// Generated by Claude Code via Playwright MCP live exploration — 2026-05-06
// Coverage: Login · Home · Events · Event Detail · Booking · My Bookings · Admin
import { test, expect } from '../fixtures/auth_fixtures';
import { LoginPage }      from '../pages/LoginPage';
import { HomePage }       from '../pages/HomePage';
import { EventsPage }     from '../pages/EventsPage';
import { EventDetailPage } from '../pages/EventDetailPage';
import { MyBookingsPage } from '../pages/MyBookingsPage';
import { AdminEventsPage } from '../pages/AdminEventsPage';

const EMAIL    = process.env.ADMIN_EMAIL    ?? '';
const PASSWORD = process.env.ADMIN_PASSWORD ?? '';
const BASE_URL = process.env.UI_BASE_URL    ?? 'https://eventhub.rahulshettyacademy.com/';

// ═══════════════════════════════════════════════════════════════════════════
// LOGIN PAGE
// ═══════════════════════════════════════════════════════════════════════════
test.describe('Login Page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`${BASE_URL}login`);
  });

  test('TC-L01: page title and heading are correct', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await expect(page).toHaveTitle(/EventHub/i);
    await expect(loginPage.pageHeading).toBeVisible();
    await expect(loginPage.subText).toBeVisible();
  });

  test('TC-L02: all form elements are visible', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await expect(loginPage.emailInput).toBeVisible();
    await expect(loginPage.passwordInput).toBeVisible();
    await expect(loginPage.signInButton).toBeVisible();
    await expect(loginPage.registerLink).toBeVisible();
  });

  test('TC-L03: password field masks input', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.passwordInput.fill('secret');
    await expect(loginPage.passwordInput).toHaveAttribute('type', 'password');
  });

  test('TC-L04: successful login redirects away from /login', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.login(EMAIL, PASSWORD);
    await page.waitForURL(url => !url.pathname.includes('/login'), { timeout: 10_000 });
    expect(page.url()).not.toContain('/login');
  });

  test('TC-L05: logged-in user email appears in navbar', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.login(EMAIL, PASSWORD);
    await page.waitForURL(url => !url.pathname.includes('/login'), { timeout: 10_000 });
    await expect(page.getByText(EMAIL)).toBeVisible();
  });

  test('TC-L06: wrong credentials shows error alert', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.login('wrong@email.com', 'WrongPass@1');
    await expect(loginPage.errorMessage).toBeVisible({ timeout: 8_000 });
    expect(page.url()).toContain('/login');
  });

  test('TC-L07: Register link navigates to /register', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.clickRegister();
    await expect(page).toHaveURL(/\/register/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// HOME PAGE
// ═══════════════════════════════════════════════════════════════════════════
test.describe('Home Page', () => {
  test.beforeEach(async ({ adminPage }) => {
    await adminPage.goto(BASE_URL);
  });

  test('TC-H01: hero section content is visible', async ({ page }) => {
    const homePage = new HomePage(page);
    await expect(homePage.heroHeading).toBeVisible();
    await expect(homePage.browseEventsLink).toBeVisible();
    await expect(homePage.myBookingsHeroBtn).toBeVisible();
  });

  test('TC-H02: Featured Events section shows 3 cards', async ({ page }) => {
    const homePage = new HomePage(page);
    await expect(homePage.featuredEventsHeading).toBeVisible();
    await expect(homePage.eventCards).toHaveCount(3);
  });

  test('TC-H03: featured event names are correct', async ({ page }) => {
    const homePage = new HomePage(page);
    await expect(homePage.eventHeading('Dilli Diwali Mela')).toBeVisible();
    await expect(homePage.eventHeading('Hollywood Monsoon Night')).toBeVisible();
    await expect(homePage.eventHeading('World Tech Summit')).toBeVisible();
  });

  test('TC-H04: navbar links are present', async ({ page }) => {
    const homePage = new HomePage(page);
    await expect(homePage.navHomeLink).toBeVisible();
    await expect(homePage.navEventsLink).toBeVisible();
    await expect(homePage.navMyBookingsLink).toBeVisible();
    await expect(homePage.navApiDocsLink).toBeVisible();
    await expect(homePage.logoutBtn).toBeVisible();
  });

  test('TC-H05: Browse Events → navigates to /events', async ({ page }) => {
    const homePage = new HomePage(page);
    await homePage.clickBrowseEvents();
    await expect(page).toHaveURL(/\/events/);
  });

  test('TC-H06: logout redirects to login page', async ({ page }) => {
    const homePage = new HomePage(page);
    await homePage.clickLogout();
    await expect(page).toHaveURL(/\/login|\/$/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// EVENTS PAGE
// ═══════════════════════════════════════════════════════════════════════════
test.describe('Events Page', () => {
  test.beforeEach(async ({ adminPage }) => {
    await adminPage.goto(`${BASE_URL}events`);
  });

  test('TC-E01: page heading and subtext are correct', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.pageHeading).toBeVisible();
    await expect(eventsPage.subText).toBeVisible();
  });

  test('TC-E02: search box is visible and accepts input', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.searchBox).toBeVisible();
    await eventsPage.searchFor('Tech');
    await expect(eventsPage.searchBox).toHaveValue('Tech');
  });

  test('TC-E03: category filter has expected options', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.categoryFilter).toBeVisible();
    const options = await eventsPage.categoryFilter.locator('option').allTextContents();
    for (const cat of ['All Categories', '🎙 Conference', '🎵 Concert', '⚽ Sports', '🛠 Workshop', '🎉 Festival']) {
      expect(options).toContain(cat);
    }
  });

  test('TC-E04: city filter has expected options', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.cityFilter).toBeVisible();
    const options = await eventsPage.cityFilter.locator('option').allTextContents();
    for (const city of ['All Cities', 'Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Chennai', 'Pune']) {
      expect(options).toContain(city);
    }
  });

  test('TC-E05: 3 event cards are listed', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.eventCards).toHaveCount(3);
  });

  test('TC-E06: each event card has Book Now link', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await expect(eventsPage.bookNowLinks).toHaveCount(3);
  });

  test('TC-E07: event prices are displayed', async ({ page }) => {
    await expect(page.getByText('$300')).toBeVisible();
    await expect(page.getByText('$2,500')).toBeVisible();
    await expect(page.getByText('$1,500')).toBeVisible();
  });

  test('TC-E08: Add New Event button links to admin', async ({ page }) => {
    const eventsPage = new EventsPage(page);
    await eventsPage.clickAddNewEvent();
    await expect(page).toHaveURL(/\/admin\/events/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// EVENT DETAIL PAGE  (World Tech Summit — /events/1)
// ═══════════════════════════════════════════════════════════════════════════
test.describe('Event Detail Page', () => {
  test.beforeEach(async ({ adminPage }) => {
    await adminPage.goto(`${BASE_URL}events/1`);
  });

  test('TC-D01: event title and badges are visible', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await expect(detailPage.eventTitle('World Tech Summit')).toBeVisible();
    await expect(detailPage.categoryBadge).toBeVisible();
    await expect(detailPage.featuredBadge).toBeVisible();
  });

  test('TC-D02: event metadata is shown', async ({ page }) => {
    await expect(page.getByText('Saturday, 18 April')).toBeVisible();
    await expect(page.getByText('02:30 pm')).toBeVisible();
    await expect(page.getByText('Hyderabad, Hitech city')).toBeVisible();
    await expect(page.getByText(/\d+ \/ 500 seats/)).toBeVisible();
    await expect(page.getByText('$1,500').first()).toBeVisible();
  });

  test('TC-D03: About this event section is present', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await expect(detailPage.aboutHeading).toBeVisible();
    await expect(page.getByText(/premier technology conference/i)).toBeVisible();
  });

  test('TC-D04: booking form is visible', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await expect(detailPage.bookTicketsHeading).toBeVisible();
    await expect(detailPage.fullNameInput).toBeVisible();
    await expect(detailPage.emailInput).toBeVisible();
    await expect(detailPage.phoneInput).toBeVisible();
    await expect(detailPage.confirmBookingBtn).toBeVisible();
  });

  test('TC-D05: ticket counter starts at 1 and decrement is disabled', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await expect(detailPage.decrementBtn).toBeDisabled();
    await expect(detailPage.incrementBtn).toBeEnabled();
  });

  test('TC-D06: increment button increases ticket count', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await detailPage.incrementTickets();
    await expect(detailPage.decrementBtn).toBeEnabled();
  });

  test('TC-D07: total price updates when tickets increase', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await expect(page.getByText('$1,500 × 1 ticket')).toBeVisible();
    await detailPage.incrementTickets();
    await expect(page.getByText('$1,500 × 2')).toBeVisible();
  });

  test('TC-D08: breadcrumb navigation back to events', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await detailPage.clickEventsLink();
    await expect(page).toHaveURL(/\/events$/);
  });

  test('TC-D09: booking form fills and submit button is enabled', async ({ page }) => {
    const detailPage = new EventDetailPage(page);
    await detailPage.fillBookingForm('Pavan Chaudhari', EMAIL, '+91 9876543210');
    await expect(detailPage.confirmBookingBtn).toBeEnabled();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// MY BOOKINGS PAGE
// ═══════════════════════════════════════════════════════════════════════════
test.describe('My Bookings Page', () => {
  test.beforeEach(async ({ adminPage }) => {
    await adminPage.goto(`${BASE_URL}bookings`);
  });

  test('TC-B01: page heading is correct', async ({ page }) => {
    const bookingsPage = new MyBookingsPage(page);
    await expect(bookingsPage.pageHeading).toBeVisible();
    await expect(bookingsPage.subText).toBeVisible();
  });

  test('TC-B02: Clear all bookings button is visible', async ({ page }) => {
    const bookingsPage = new MyBookingsPage(page);
    await expect(bookingsPage.clearAllBookingsBtn).toBeVisible();
  });

  test('TC-B03: empty state shows correct message when no bookings', async ({ page }) => {
    const bookingsPage = new MyBookingsPage(page);
    if (!(await bookingsPage.hasBookings())) {
      await expect(bookingsPage.noBookingsHeading).toBeVisible();
      await expect(bookingsPage.browseEventsBtn).toBeVisible();
    }
  });

  test('TC-B04: Browse Events button navigates to /events', async ({ page }) => {
    const bookingsPage = new MyBookingsPage(page);
    if (await bookingsPage.browseEventsBtn.isVisible()) {
      await bookingsPage.clickBrowseEvents();
      await expect(page).toHaveURL(/\/events/);
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// ADMIN — MANAGE EVENTS PAGE
// ═══════════════════════════════════════════════════════════════════════════
test.describe('Admin Manage Events Page', () => {
  test.beforeEach(async ({ adminPage }) => {
    await adminPage.goto(`${BASE_URL}admin/events`);
  });

  test('TC-A01: Add New Event form fields are present', async ({ page }) => {
    const adminPage = new AdminEventsPage(page);
    await expect(adminPage.newEventHeading).toBeVisible();
    await expect(adminPage.titleInput).toBeVisible();
    await expect(adminPage.descriptionInput).toBeVisible();
    await expect(adminPage.firstSelect).toBeVisible();
    await expect(adminPage.cityInput).toBeVisible();
    await expect(adminPage.venueInput).toBeVisible();
    await expect(adminPage.addEventBtn).toBeVisible();
  });

  test('TC-A02: category dropdown has correct options', async ({ page }) => {
    const adminEventsPage = new AdminEventsPage(page);
    const dropdown = adminEventsPage.categoryDropdown;
    for (const opt of ['Conference', 'Concert', 'Sports', 'Workshop', 'Festival']) {
      await expect(dropdown.locator(`option:text-is("${opt}")`)).toHaveCount(1);
    }
  });

  test('TC-A03: All Events table shows 3 rows', async ({ page }) => {
    const adminEventsPage = new AdminEventsPage(page);
    await expect(adminEventsPage.allEventsHeading).toBeVisible();
    await expect(page.getByText('3 total')).toBeVisible();
    await expect(adminEventsPage.tableRows).toHaveCount(3);
  });

  test('TC-A04: table columns are correct', async ({ page }) => {
    const adminEventsPage = new AdminEventsPage(page);
    for (const col of ['Title', 'Category', 'City', 'Date', 'Price', 'Seats', 'Actions']) {
      await expect(adminEventsPage.columnHeader(col)).toBeVisible();
    }
  });

  test('TC-A05: featured events show Read-only in Actions column', async ({ page }) => {
    const readOnlyCells = page.locator('td').filter({ hasText: 'Read-only' });
    await expect(readOnlyCells).toHaveCount(3);
  });

  test('TC-A06: all 3 events appear in table', async ({ page }) => {
    const adminEventsPage = new AdminEventsPage(page);
    await expect(adminEventsPage.eventCell(/Dilli Diwali Mela/)).toBeVisible();
    await expect(adminEventsPage.eventCell(/Hollywood Monsoon Night/)).toBeVisible();
    await expect(adminEventsPage.eventCell(/World Tech Summit/)).toBeVisible();
  });

  test('TC-A07: event limit notice is displayed', async ({ page }) => {
    await expect(page.getByText(/6 events/)).toBeVisible();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// END-TO-END: Book a ticket and verify in My Bookings
// ═══════════════════════════════════════════════════════════════════════════
test.describe('E2E: Book ticket flow', () => {
  test('TC-F01: book World Tech Summit and verify booking appears', async ({ adminPage }) => {
    const bookingsPage = new MyBookingsPage(adminPage);
    const detailPage   = new EventDetailPage(adminPage);

    // Clear any prior bookings for a clean state
    await bookingsPage.goto(BASE_URL);
    await bookingsPage.clearAllBookings();

    // Navigate to event detail and complete booking
    await detailPage.goto(BASE_URL, 1);
    await detailPage.fillBookingForm('Pavan Chaudhari', EMAIL, '+91 9876543210');
    await detailPage.clickConfirmBooking();

    // Should navigate to bookings or show confirmation
    await adminPage.waitForURL(/\/bookings|\/events\/1/, { timeout: 10_000 });

    // Verify booking appears in My Bookings
    await bookingsPage.goto(BASE_URL);
    await expect(bookingsPage.noBookingsHeading).not.toBeVisible({ timeout: 8_000 });
  });
});
